In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3,4])#rank 1 array
print(a)
print(type(a))
print(id(a))

[1 2 3 4]
<class 'numpy.ndarray'>
2987491646480


In [7]:
print(a.shape)
print(a[0],a[2:])
a[0]=5
print(id(a))

(4,)
1 [3 4]
2987491646480


In [8]:
a=np.array([[1,2,3],[4,5,6]])# rank 2 array
print(a.shape)

(2, 3)


In [9]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
print(a[1,1])
a[0,2]

5


3

In [14]:
a=np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [15]:
a=np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
e=np.random.random((2,3))
e

array([[0.0552726 , 0.93282075, 0.37131311],
       [0.79704201, 0.77501014, 0.72848442]])

In [18]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(a.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


Fetch the matrix from above array a

[[2,3]

[6,7]]

In [23]:
# b=a[rows,columns]
b=a[0:2,1:3]
b

array([[2, 3],
       [6, 7]])

In [26]:
bool_idx=(a<=2)
bool_idx

array([[ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [27]:
a[(a<=2)] # array of true values

array([1, 2])

In [29]:
x=np.array([1,3,5.8],dtype=np.int64)
print(x.dtype)

int64


In [30]:
x

array([1, 3, 5], dtype=int64)

In [32]:
a.ndim

2